- name: Check that old keys don't exist
  ansible.builtin.fail:
    msg: >
      You're still defining keys for an older version of yggdrasil.
      Please update your host vars.
  when: >
    yggdrasil_encryption_public_key is defined
    or yggdrasil_encryption_private_key is defined
    or yggdrasil_signing_public_key is defined
    or yggdrasil_signing_private_key is defined

- name: Check that keys exist
  ansible.builtin.fail:
    msg: >
      The keys for yggdrasil are missing. Please generate them and
      put them into `yggdrasil_public_key` and `yggdrasil_private_key`
  when: >
    yggdrasil_public_key is not defined
    or yggdrasil_private_key is not defined
