galaxy_info:
  author: Jan Christian Gr√ºnhage <jan.christian@gruenhage.xyz>
  description: Deploys a containerized traefik instance

  license: AGPLv3

  min_ansible_version: "2.5"

  platforms:
    - name: Debian
      versions:
        - "all"

  galaxy_tags: []

dependencies: []
